// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package org.wcx.dfs.namenode.rpc.service;

public final class NameNodeRpcServer {
  private NameNodeRpcServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022\030org.wcx.dfs.n" +
      "amenode.rpc\032\026NameNodeRpcModel.proto2\332\001\n\017" +
      "NameNodeService\022a\n\010register\022).org.wcx.df" +
      "s.namenode.rpc.RegisterRequest\032*.org.wcx" +
      ".dfs.namenode.rpc.RegisterResponse\022d\n\the" +
      "artbeat\022*.org.wcx.dfs.namenode.rpc.Heart" +
      "beatRequest\032+.org.wcx.dfs.namenode.rpc.H" +
      "eartbeatResponseB7\n org.wcx.dfs.namenode" +
      ".rpc.serviceB\021NameNodeRpcServerP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.wcx.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor(),
        }, assigner);
    org.wcx.dfs.namenode.rpc.model.NameNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
